using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace Odc;

public sealed record OdcChunk(ushort Type, ushort Flags, ulong Length, long HeaderOffset, long DataOffset);
public sealed record OdcInfo(string Version,uint Flags,uint ChunkCount,string FileName,string MimeType,ulong OriginalSize,ulong StoredPayloadSize,string Compression,string Sha256,JsonElement? Metadata,IReadOnlyList<OdcChunk> Chunks);

public static class OdcContainer
{
    const int Header=24, Ch=12; const ushort FileName=1,Mime=2,Meta=3,OriginalSize=4,CompressionType=0x10,Sha=0x20,Payload=0x100;
    static void W16(BinaryWriter w,ushort v)=>w.Write(v); static void W32(BinaryWriter w,uint v)=>w.Write(v); static void W64(BinaryWriter w,ulong v)=>w.Write(v);
    static void WriteChunk(BinaryWriter w,ushort t,ReadOnlySpan<byte> data){W16(w,t);W16(w,0);W64(w,(ulong)data.Length);w.Write(data);}
    static string MimeOf(string p)=>Path.GetExtension(p).ToLowerInvariant() switch{ ".txt"=>"text/plain", ".json"=>"application/json", ".xml"=>"application/xml", ".csv"=>"text/csv", ".jpg" or ".jpeg"=>"image/jpeg", ".png"=>"image/png", ".webp"=>"image/webp", ".pdf"=>"application/pdf", ".zip"=>"application/zip", _=>"application/octet-stream"};
    static bool TryGzip(string m,long n)=>n>=768&&(m.StartsWith("text/")||m is "application/json" or "application/xml" or "application/javascript" or "application/sql"||m.EndsWith("+json")||m.EndsWith("+xml"));

    public static void Create(string input,string output,object? metadata=null,bool compress=true){var raw=File.ReadAllBytes(input);var mime=MimeOf(input);byte[] payload=raw;byte comp=0;if(compress&&TryGzip(mime,raw.LongLength)){using var ms=new MemoryStream();using(var gz=new GZipStream(ms,CompressionLevel.Optimal,true))gz.Write(raw);var z=ms.ToArray();if(z.Length+64<raw.Length){payload=z;comp=1;}}var hash=SHA256.HashData(raw);Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);var tmp=output+".tmp-"+Guid.NewGuid().ToString("N");using(var f=File.Create(tmp))using(var w=new BinaryWriter(f,Encoding.UTF8,true)){w.Write(Encoding.ASCII.GetBytes("ODC1"));W16(w,1);W16(w,0);W32(w,comp==1?1u:0);W32(w,24);W32(w,(uint)(6+(metadata is null?0:1)));W32(w,0);WriteChunk(w,FileName,Encoding.UTF8.GetBytes(Path.GetFileName(input)));WriteChunk(w,Mime,Encoding.UTF8.GetBytes(mime));if(metadata is not null)WriteChunk(w,Meta,Encoding.UTF8.GetBytes(JsonSerializer.Serialize(metadata)));Span<byte>s=stackalloc byte[8];BitConverter.TryWriteBytes(s,(ulong)raw.LongLength);WriteChunk(w,OriginalSize,s);WriteChunk(w,CompressionType,new[]{comp});WriteChunk(w,Sha,hash);WriteChunk(w,Payload,payload);}File.Move(tmp,output,true);}

    public static (uint Flags,List<OdcChunk> Chunks) Scan(string p){using var f=File.OpenRead(p);using var r=new BinaryReader(f,Encoding.UTF8,true);if(f.Length<Header||Encoding.ASCII.GetString(r.ReadBytes(4))!="ODC1")throw new InvalidDataException("ODC inválido");var major=r.ReadUInt16();r.ReadUInt16();var flags=r.ReadUInt32();var hs=r.ReadUInt32();var count=r.ReadUInt32();r.ReadUInt32();if(major!=1||hs!=Header||count>1_000_000)throw new InvalidDataException("header não suportado");var list=new List<OdcChunk>();for(uint i=0;i<count;i++){var ho=f.Position;if(ho+Ch>f.Length)throw new InvalidDataException("chunk truncado");var t=r.ReadUInt16();var fl=r.ReadUInt16();var len=r.ReadUInt64();var d=f.Position;if(len>(ulong)(f.Length-d))throw new InvalidDataException("comprimento inválido");list.Add(new(t,fl,len,ho,d));f.Position=d+(long)len;}return(flags,list);}
    static OdcChunk Find(List<OdcChunk> c,ushort t)=>c.FirstOrDefault(x=>x.Type==t)??throw new InvalidDataException($"chunk ausente {t:X4}"); static byte[] ReadSmall(string p,List<OdcChunk> c,ushort t,int max,bool req=true){var x=c.FirstOrDefault(z=>z.Type==t);if(x is null){if(req)throw new InvalidDataException("chunk ausente");return [];}if(x.Length>(ulong)max)throw new InvalidDataException("chunk grande demais");using var f=File.OpenRead(p);f.Position=x.DataOffset;var b=new byte[(int)x.Length];f.ReadExactly(b);return b;}
    public static OdcInfo Info(string p){var(flags,c)=Scan(p);var fn=Encoding.UTF8.GetString(ReadSmall(p,c,FileName,1<<20));var mt=Encoding.UTF8.GetString(ReadSmall(p,c,Mime,1<<20));var sz=BitConverter.ToUInt64(ReadSmall(p,c,OriginalSize,8));var cp=ReadSmall(p,c,CompressionType,1)[0];var sh=Convert.ToHexString(ReadSmall(p,c,Sha,32)).ToLowerInvariant();var mb=ReadSmall(p,c,Meta,16<<20,false);JsonElement? meta=mb.Length==0?null:JsonSerializer.Deserialize<JsonElement>(mb);var pl=Find(c,Payload);return new("1.0",flags,(uint)c.Count,fn,mt,sz,pl.Length,cp==1?"gzip":"none",sh,meta,c);}
    public static void Extract(string p,string output){var(_,c)=Scan(p);var pl=Find(c,Payload);using var f=File.OpenRead(p);f.Position=pl.DataOffset;using var sec=new MemoryStream();var buf=new byte[81920];ulong rem=pl.Length;while(rem>0){var n=f.Read(buf,0,(int)Math.Min((ulong)buf.Length,rem));if(n<=0)throw new EndOfStreamException();sec.Write(buf,0,n);rem-=(ulong)n;}var cp=ReadSmall(p,c,CompressionType,1)[0];sec.Position=0;Stream source=sec;GZipStream? gz=null;if(cp==1){gz=new GZipStream(sec,CompressionMode.Decompress,true);source=gz;}else if(cp!=0)throw new InvalidDataException("compressão não suportada");Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);using(var o=File.Create(output))source.CopyTo(o);gz?.Dispose();var raw=File.ReadAllBytes(output);var size=BitConverter.ToUInt64(ReadSmall(p,c,OriginalSize,8));if((ulong)raw.Length!=size)throw new InvalidDataException("tamanho divergente");if(!CryptographicOperations.FixedTimeEquals(SHA256.HashData(raw),ReadSmall(p,c,Sha,32)))throw new InvalidDataException("SHA-256 inválido");}
    public static bool Verify(string p){var t=Path.GetTempFileName();try{Extract(p,t);return true;}catch{return false;}finally{File.Delete(t);}}
    public static void SetMetadata(string p,object? metadata){var i=Info(p);var tmp=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N")+Path.GetExtension(i.FileName));Extract(p,tmp);try{Create(tmp,p,metadata,i.Compression=="gzip");}finally{File.Delete(tmp);}}
}
