<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ODC-Studio-DotNet</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Odc/Odc.csproj" />
  </ItemGroup>
</Project>
