use flate2::{read::GzDecoder, write::GzEncoder, Compression};
use serde::Serialize;
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::{fs, io::{Read, Write}, path::Path};

pub const HEADER: usize = 24;
pub const CH: usize = 12;
pub const FILE_NAME:u16=0x0001; pub const MIME:u16=0x0002; pub const META:u16=0x0003; pub const ORIGINAL_SIZE:u16=0x0004;
pub const COMPRESSION:u16=0x0010; pub const SHA256:u16=0x0020; pub const PAYLOAD:u16=0x0100;

#[derive(Debug, Clone, Serialize)] pub struct Chunk { pub chunk_type:u16, pub flags:u16, pub length:u64, pub header_offset:u64, pub data_offset:u64 }
#[derive(Debug, Serialize)] pub struct OdcInfo { pub version:String, pub flags:u32, pub chunk_count:u32, pub file_name:String, pub mime_type:String, pub original_size:u64, pub stored_payload_size:u64, pub compression:String, pub sha256:String, pub metadata:Option<Value>, pub chunks:Vec<Chunk> }
fn le16(b:&[u8])->u16{u16::from_le_bytes([b[0],b[1]])} fn le32(b:&[u8])->u32{u32::from_le_bytes(b.try_into().unwrap())} fn le64(b:&[u8])->u64{u64::from_le_bytes(b.try_into().unwrap())}
fn put_chunk(out:&mut Vec<u8>,t:u16,data:&[u8]){out.extend_from_slice(&t.to_le_bytes());out.extend_from_slice(&0u16.to_le_bytes());out.extend_from_slice(&(data.len() as u64).to_le_bytes());out.extend_from_slice(data);}
fn should_gzip(m:&str,n:usize)->bool{n>=768&&(m.starts_with("text/")||matches!(m,"application/json"|"application/xml"|"application/javascript"|"application/sql")||m.ends_with("+json")||m.ends_with("+xml"))}

pub fn scan(data:&[u8])->Result<(u32,Vec<Chunk>),String>{ if data.len()<HEADER||&data[..4]!=b"ODC1"{return Err("ODC inválido/truncado".into())} let major=le16(&data[4..6]);let flags=le32(&data[8..12]);let hs=le32(&data[12..16]);let count=le32(&data[16..20]);if major!=1||hs!=24||count>1_000_000{return Err("header não suportado".into())} let mut p=24usize;let mut v=Vec::new();for _ in 0..count{if p+CH>data.len(){return Err("chunk truncado".into())}let t=le16(&data[p..p+2]);let f=le16(&data[p+2..p+4]);let l=le64(&data[p+4..p+12]);let d=p+CH;if l>usize::MAX as u64||d.checked_add(l as usize).map_or(true,|e|e>data.len()){return Err("comprimento inválido".into())}v.push(Chunk{chunk_type:t,flags:f,length:l,header_offset:p as u64,data_offset:d as u64});p=d+l as usize;}Ok((flags,v))}
fn one<'a>(data:&'a[u8],ch:&[Chunk],t:u16,max:u64,required:bool)->Result<Option<&'a[u8]>,String>{if let Some(c)=ch.iter().find(|c|c.chunk_type==t){if c.length>max{return Err("chunk acima do limite".into())}let s=c.data_offset as usize;return Ok(Some(&data[s..s+c.length as usize]))}if required{Err(format!("chunk ausente {t:04x}"))}else{Ok(None)}}

pub fn create_from_file(input:&Path,output:&Path,metadata:Option<&Value>,compress:bool)->Result<(),String>{let raw=fs::read(input).map_err(|e|e.to_string())?;let mime=mime_guess::from_path(input).first_or_octet_stream().essence_str().to_string();let mut payload=raw.clone();let mut comp=0u8;if compress&&should_gzip(&mime,raw.len()){let mut e=GzEncoder::new(Vec::new(),Compression::default());e.write_all(&raw).map_err(|e|e.to_string())?;let gz=e.finish().map_err(|e|e.to_string())?;if gz.len()+64<raw.len(){payload=gz;comp=1}}let hash=Sha256::digest(&raw);let count=6+u32::from(metadata.is_some());let mut out=Vec::with_capacity(payload.len()+512);out.extend_from_slice(b"ODC1");out.extend_from_slice(&1u16.to_le_bytes());out.extend_from_slice(&0u16.to_le_bytes());out.extend_from_slice(&(if comp==1{1u32}else{0}).to_le_bytes());out.extend_from_slice(&24u32.to_le_bytes());out.extend_from_slice(&count.to_le_bytes());out.extend_from_slice(&0u32.to_le_bytes());put_chunk(&mut out,FILE_NAME,input.file_name().unwrap_or_default().to_string_lossy().as_bytes());put_chunk(&mut out,MIME,mime.as_bytes());if let Some(m)=metadata{put_chunk(&mut out,META,serde_json::to_string(m).map_err(|e|e.to_string())?.as_bytes())}put_chunk(&mut out,ORIGINAL_SIZE,&(raw.len() as u64).to_le_bytes());put_chunk(&mut out,COMPRESSION,&[comp]);put_chunk(&mut out,SHA256,&hash);put_chunk(&mut out,PAYLOAD,&payload);if let Some(p)=output.parent(){fs::create_dir_all(p).map_err(|e|e.to_string())?}let tmp=output.with_extension("odc.tmp");fs::write(&tmp,out).map_err(|e|e.to_string())?;if output.exists(){fs::remove_file(output).map_err(|e|e.to_string())?}fs::rename(tmp,output).map_err(|e|e.to_string())?;Ok(())}

pub fn info_file(path:&Path)->Result<OdcInfo,String>{let d=fs::read(path).map_err(|e|e.to_string())?;let(flags,ch)=scan(&d)?;let f=String::from_utf8_lossy(one(&d,&ch,FILE_NAME,1<<20,true)?.unwrap()).into_owned();let m=String::from_utf8_lossy(one(&d,&ch,MIME,1<<20,true)?.unwrap()).into_owned();let sz=le64(one(&d,&ch,ORIGINAL_SIZE,8,true)?.unwrap());let cp=one(&d,&ch,COMPRESSION,1,true)?.unwrap()[0];let sh=hex::encode(one(&d,&ch,SHA256,32,true)?.unwrap());let p=ch.iter().find(|c|c.chunk_type==PAYLOAD).ok_or("PAYLOAD ausente")?;let meta=match one(&d,&ch,META,16<<20,false)?{Some(b)=>Some(serde_json::from_slice(b).map_err(|e|e.to_string())?),None=>None};Ok(OdcInfo{version:"1.0".into(),flags,chunk_count:ch.len() as u32,file_name:f,mime_type:m,original_size:sz,stored_payload_size:p.length,compression:if cp==1{"gzip".into()}else{"none".into()},sha256:sh,metadata:meta,chunks:ch})}

pub fn extract(path:&Path,out:&Path)->Result<(),String>{let d=fs::read(path).map_err(|e|e.to_string())?;let(_,ch)=scan(&d)?;let p=ch.iter().find(|c|c.chunk_type==PAYLOAD).ok_or("PAYLOAD ausente")?;let s=p.data_offset as usize;let packed=&d[s..s+p.length as usize];let cp=one(&d,&ch,COMPRESSION,1,true)?.unwrap()[0];let raw=if cp==1{let mut gz=GzDecoder::new(packed);let mut v=Vec::new();gz.read_to_end(&mut v).map_err(|e|e.to_string())?;v}else if cp==0{packed.to_vec()}else{return Err("compressão não suportada".into())};let sz=le64(one(&d,&ch,ORIGINAL_SIZE,8,true)?.unwrap());if raw.len() as u64!=sz{return Err("tamanho divergente".into())}let expected=one(&d,&ch,SHA256,32,true)?.unwrap();let actual=Sha256::digest(&raw);if expected!=actual.as_slice(){return Err("SHA-256 inválido".into())}if let Some(p)=out.parent(){fs::create_dir_all(p).map_err(|e|e.to_string())?}fs::write(out,raw).map_err(|e|e.to_string())}
pub fn verify(path:&Path)->bool{let tmp=std::env::temp_dir().join(format!("odc-verify-{}",std::process::id()));let r=extract(path,&tmp).is_ok();let _=fs::remove_file(tmp);r}
pub fn set_metadata(path:&Path,meta:Option<&Value>)->Result<(),String>{let info=info_file(path)?;let tmp=std::env::temp_dir().join(&info.file_name);extract(path,&tmp)?;let r=create_from_file(&tmp,path,meta,info.compression=="gzip");let _=fs::remove_file(tmp);r}
